{
    "sample": {
        "prog_id": 34,
        "prog_name": "sieve",
        "language": "python",
        "testcase_num": 6,
        "fault_location": 3,
        "bug_type": "",
        "bug_detail_desc": "在判斷n是否不被所有質數整除時，寫成了是否存在質數不能整除n，由於始終不存在質數用於判斷，導致除了max=1以外的狀況全部出錯"
    },
    "patchs_eval": [
        {
            "run_time": 13.019552946090698,
            "is_plausible": true,
            "is_correct": false,
            "pass_num": 6,
            "fail_num": 0,
            "reparied_code": "def sieve(max):\n    primes = []\n    for n in range(2, max + 1):\n        if all(n % p != 0 for p in primes):\n            primes.append(n)\n    return primes\nmax_val = 30\nprint(f\"Primes up to {max_val}:\", sieve(max_val))"
        },
        {
            "run_time": 15.308001041412354,
            "is_plausible": true,
            "is_correct": false,
            "pass_num": 6,
            "fail_num": 0,
            "reparied_code": "def sieve(max):\n    primes = []\n    for n in range(2, max + 1):\n        if all(n % p != 0 for p in primes):\n            primes.append(n)\n    return primes"
        },
        {
            "run_time": 24.745332956314087,
            "is_plausible": true,
            "is_correct": false,
            "pass_num": 6,
            "fail_num": 0,
            "reparied_code": "def sieve(max):\n    primes = []\n    for n in range(2, max + 1):\n        if all(n % p != 0 for p in primes):\n            primes.append(n)\n    return primes"
        }
    ]
}