{
    "sample": {
        "prog_id": 17,
        "prog_name": "lis",
        "language": "python",
        "testcase_num": 12,
        "fault_location": 12,
        "bug_type": "",
        "bug_detail_desc": "在更改longest變數時，缺少了max函數判斷新數值是否比原本長，導致在初期就找到答案的情況會在後期被更新為錯誤答案"
    },
    "patchs_eval": [
        {
            "run_time": 2.7257590293884277,
            "pass_num": 9,
            "fail_num": 3,
            "reparied_code": "\ndef lis(arr):\n    ends = {0: -1}\n    longest = 0\n\n    for i, val in enumerate(arr):\n\n        prefix_lengths = [j for j in range(1, longest + 1) if arr[ends[j]] < val]\n\n        length = max(prefix_lengths) if prefix_lengths else 0\n\n        if length == longest or val < arr[ends[length]]:\n            ends[length + 1] = i\n            longest = length + 1\n\n    return longest"
        },
        {
            "run_time": 2.6635351181030273,
            "pass_num": 9,
            "fail_num": 3,
            "reparied_code": "\ndef lis(arr):\n    ends = {0: -1}\n    longest = 0\n\n    for i, val in enumerate(arr):\n\n        prefix_lengths = [j for j in range(longest + 1) if arr[ends[j]] < val]\n\n        length = max(prefix_lengths, default=0)\n\n        if length == longest or val < arr[ends[length]]:\n            ends[length+1] = i\n            longest = length + 1\n\n    return longest"
        },
        {
            "run_time": 2.5625221729278564,
            "pass_num": 9,
            "fail_num": 3,
            "reparied_code": "\ndef lis(arr):\n    ends = {0: -1}\n    longest = 0\n\n    for i, val in enumerate(arr):\n        prefix_lengths = [j for j in range(longest + 1) if arr[ends[j]] < val]\n        length = max(prefix_lengths, default=0)\n\n        if length == longest or val < arr[ends[length]]:\n            ends[length + 1] = i\n            longest = length + 1\n\n    return longest"
        }
    ]
}